server:
  port: 0

spring:
  application:
    name: tollrate-service

application:
  title: tollrate-service

eureka:
  client:
    healthcheck:
      enabled: true
    fetch-registry: false
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost