spring:
  application:
    name: spring-ai-workshop
  ai:
    chat:
      client:
        enabled: false
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: gpt-4o
    anthropic:
      api-key: {ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-sonnet-4-20250514

